# Site settings
title: 欢迎到Roger博客
email: cwjackk@163.com
description: > # this means to ignore newlines until "baseurl:"
  不愿变渣的N个理由
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
# twitter:  username
# weibo:    ID
github:   cwj-rogers
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
kramdown:
 input: GFM
highlighter: rouge

sass:
  style: compressed
gems:
  - jekyll-sitemap
